language: ruby
sudo: false
cache: bundler
rvm: 2.2.2
install: bundle install
script:
- bundle exec jekyll build --config _config_dev.yml
- bundle exec htmlproofer ./_site --disable-external --alt-ignore "\/images\/.*.gif"
- bundle exec jekyll clean
- bundle exec jekyll build --config _config_omero_plus.yml
after_success:
- mkdir _dist
- tar Jcf "_dist/_site-${TRAVIS_COMMIT}.tar.xz" _site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: "CQY8cjim3hA2WlyqZR2xu9Gq/wrqdfd0iM/Ex3HPnUitf04l7eCp8VOqYnkyRq+OuUVpybhz51apo3QkC2Xm/5zQioSgFYNObARzBfvBkT7edjL1jB5WQKvAYaXy7esVah+sct7j+zuuFjeKVLS+Li1U05hOjurcRFM/7Wz8aLccjEd2YcJVt2C1MNPLZebo4mkdc1pannMxMqP10NGCwC4TqikHixVvGOwC9lPSqWoMIxSgW38zmKp7P3jE5cukDLNPj6/8kHsJuu4JvDxsffcyDTXWto75+vDTOnlOGpX2f8Z5fkvbrXpNkFsWZDZRmcI2jJKWUyoCI94Ad9QFn7n/yVnDUCXC/dx/eLy8PdzKqTgM/ad9t2ZrePmYKVuinMbC5QB30NCtljaDfoWUSZ7IjFRX0t2h0PITfumuuCke1PPhY6WdVH/9ibzE5yQq4ZjCcWS6BACaUaTRglOpe4wPlUOl8GZWkDv9wSveS9kWQjfqU7AMvre01BGC913pYFZ93+S2/aT4bDRxN9No6zNt4WYSx6OLwWK2Ot/WNNsswpFv/yjgYgACWeehgW5vbUiAL+kCI/sPKb8lJHRskedkwW8YUzMjcSKPUZfdgUVVBf9ZaRNAsfLHqAXeBSPmT+D0MLbYN2EGe5T3HxJS+w3wJir73IlygubX76l2KSw="
  - secure: "viIPTwKGspDYrk01e7rgYtqX3AVOYL6gCljTgJAtnhYj32uFYDAwizLnBs6vP63IQlngZoz8EU790B8dv0C+DMCew6H5S6bErBQ7Uinrq/pP1bFigIJkpxrJldLBGF34sXbrJ/Yr0Lh3PTY/7WCsB/hHLkNlOpP+4WNQ+Q06+yCi6CX6a/RY/FG59pRXSRBAKaUwdEKC87oK02iBi2bWIb3MhRwBDsaKe+KUuPHxPgRX6TvtJTD9gRTa1ZoDQimTWb54yBRDtDhHlbL+ZJdJN20+ILHwaPPrkAxD9KpgM4tdLV7/BF4KaqSsuoDFOZRk/vT1oKIHLLan7jxG99u1sDOmKHQmx7xg9CQ78SJ3GcvfkWFeWsiXYIjHLe5LULz2d+SvDC85cmX/NbjECQiGnTtCEKTIsHyaKThQgEAKV53efhiPVGh0RV/SOYzpNmm5DkkWnOkFx/60dARQ+rUz//VNxgeEantjoZbW0pwut891ER9VbCgolOwm2r822i7ddSGSU++jHk0GQPRq6nXdqxQJvr0DDGna+c9X/hefr/Hh2znG2Yfm2uDedlGM/mWGv9y5hQkWGCM8lMDe1pmBlEG1DLpGLONDMKrM99gRUxOgcBHDZ4qQE+VBo0NapO2pDlh/1DzwqtFuiGF53SdnUQ/y14k0A249LFo/xOrPxUU="
deploy:
  provider: s3
  access_key_id: AKIAJ6ZEDCM762QSIERQ
  secret_access_key:
    secure: q9eibV+ASDGzNG8U0Cu0ZLl4SGZ4TXM1pyDgD4Gz8byF4Rgdf21/NPIhcQULq+orDKsiDCENyKmJ3+aKF25iDbHhMMx7wb5/1IfhKmJb0K55a6vObtZGm49OOq9UuyvId/idFVjNCoTIqKO5dyGG+vVy1uCzVtuPfsalGTAjq0hPrB2k/vTDBjixCx8pfh5AWaU8XFNPVGsCLaNSISOadH64ecb1SvPclFHh1ChERWlEFD4iCErmbPAPHRz3Xs76EJ/iOZ4dfVKxhyUIn16o4JxOW6J6Nh6Ka9J7CAIzjafpMQjPMb56xAaIdu7eLvFrdr+AC2Frd4bXrTT8HpZze+S45RuK84ee7LHiMKRCK3teQvbFxAgnIgSlVF1OBou8SJK/pPAId65FRePStwk/pbLYrgdmWBSmluqkh8Vyhf0NNgoXAchx/VqX9/3fw8Xu1F6JkzuJNOEfqqDx0lGqh6pG6iMT8YIaMDgB3LVBiiKfWBAVm+voW8YohjI3BnQBSkHasXiWJzAWwjUWR1kBsP7YLnBBz8TQq0xBvj5GP6JV+CX5JgygkEALmA23a+SaB93KTos5BW/KxvWXlQhxcrSzHA9CUDO09aLnXXvAaeGhXpDZlDdXJDKp14BAsSLA7/yt0aaymSFMNjahBh+slKohXfOCtV9ZSLLX47hcNP8=
  bucket: ome-help-bundles
  region: us-east-1
  skip_cleanup: true
  local_dir: _dist
  on:
    repo: glencoesoftware/ome-help
    branch: dev_5_2
after_deploy:
- ./deploy.sh
